"""Generate the base technical project summary from repository context.

Run as ``python3 -m src.project_summary_generator`` (add ``--force`` to
regenerate an existing baseline).

Produces ``artifacts/summaries/base_original_summary.md`` — the immutable
baseline of the new pipeline — with deterministic Markdown headings, and
initializes ``base_updated_summary.md`` as a copy when it does not exist yet.
The baseline is never modified during normal update runs; only ``--force``
(or deleting the file) regenerates it.

Providers are pluggable: :class:`LocalDeterministicSummaryProvider` needs no
network or tokens and is the default; :class:`CopilotSummaryProvider` is a
placeholder for the future Copilot/LLM integration and is never required.
"""

from __future__ import annotations

import argparse
import os
import shutil
from pathlib import Path
from typing import Protocol

from src.repo_context_collector import RepoContext, collect_repo_context

SUMMARIES_DIRECTORY = Path("artifacts") / "summaries"
ORIGINAL_SUMMARY_NAME = "base_original_summary.md"
UPDATED_SUMMARY_NAME = "base_updated_summary.md"

# The stable heading set every generated summary must contain.
SUMMARY_HEADINGS = [
    "System Overview",
    "Repository Structure",
    "Core Modules",
    "Automation Pipeline",
    "Testing Strategy",
    "Configuration",
    "Deployment and CI",
    "Known Limitations",
]

COPILOT_TOKEN_ENV_VAR = "TECHDOCKER_COPILOT_TOKEN"


def original_summary_path(repo_path: str | Path = ".") -> Path:
    return Path(repo_path) / SUMMARIES_DIRECTORY / ORIGINAL_SUMMARY_NAME


def updated_summary_path(repo_path: str | Path = ".") -> Path:
    return Path(repo_path) / SUMMARIES_DIRECTORY / UPDATED_SUMMARY_NAME


class SummaryProvider(Protocol):
    """Interface every summary provider implements."""

    def generate_summary(self, context: RepoContext) -> str:
        """Return the full project summary as Markdown."""
        ...


class LocalDeterministicSummaryProvider:
    """Token-free provider: builds the summary directly from the context.

    Deliberately deterministic (no timestamps in the body) so tests and
    demo runs are stable and repeatable.
    """

    def generate_summary(self, context: RepoContext) -> str:
        tree = context.file_tree
        python_sources = [p for p in tree if p.startswith("src/") and p.endswith(".py")]
        test_files = [p for p in tree if p.startswith("tests/") and p.endswith(".py")]
        workflows = [p for p in tree if p.startswith(".github/workflows/")]
        configs = [
            p
            for p in tree
            if p.endswith((".json", ".toml", ".ini", ".cfg"))
            or p in ("requirements.txt",)
        ]
        automation_modules = [
            p
            for p in python_sources
            if any(k in p for k in ("automation", "updater", "router", "detector"))
        ]

        readme_excerpt = ""
        for path, content in context.files.items():
            if Path(path).name.lower() == "readme.md":
                for line in content.splitlines():
                    stripped = line.strip()
                    if stripped and not stripped.startswith("#"):
                        readme_excerpt = stripped
                        break
                break

        def bullets(paths: list[str], empty: str) -> str:
            if not paths:
                return empty
            return "\n".join(f"- `{p}`" for p in paths)

        tree_block = "\n".join(tree[:60])

        return f"""# Project Technical Summary

_Generated by TechDocker (deterministic local provider)._

## System Overview

{context.project_name} is a Python project with {context.total_files} tracked files.
{readme_excerpt or "No README description was found."}

## Repository Structure

```text
{tree_block}
```

## Core Modules

{bullets(python_sources, "No Python modules under src/ were found.")}

## Automation Pipeline

{bullets(automation_modules, "No automation-related modules were detected.")}

## Testing Strategy

{len(test_files)} test file(s) under tests/:

{bullets(test_files, "No test files were found.")}

## Configuration

{bullets(configs, "No configuration files were detected.")}

## Deployment and CI

{bullets(workflows, "No CI workflow configuration was detected.")}

## Known Limitations

- This summary was generated by the deterministic local provider, not an LLM;
  section prose is structural rather than semantic.
- Copilot/LLM-based summary generation is a future provider behind the same
  interface.
- Official project documents are not accessed due to security restrictions;
  the repository itself is the only source.
"""


class CopilotSummaryProvider:
    """Placeholder for future Copilot/LLM summary generation.

    Reads its token from the ``TECHDOCKER_COPILOT_TOKEN`` environment variable
    when present. Never required by tests or local demos.
    """

    def __init__(self, token: str | None = None) -> None:
        self.token = token or os.environ.get(COPILOT_TOKEN_ENV_VAR)

    def is_available(self) -> bool:
        return bool(self.token)

    def generate_summary(self, context: RepoContext) -> str:
        raise NotImplementedError(
            "Copilot summary generation is a future phase; use "
            "LocalDeterministicSummaryProvider for now."
        )


def get_default_provider() -> SummaryProvider:
    """The provider used when none is passed: always the deterministic one."""
    return LocalDeterministicSummaryProvider()


def generate_original_summary(
    repo_path: str | Path = ".",
    force: bool = False,
    provider: SummaryProvider | None = None,
) -> Path:
    """Write the baseline summary (and initialize the updated copy).

    Refuses to overwrite an existing ``base_original_summary.md`` unless
    ``force`` is set. Always ensures ``base_updated_summary.md`` exists,
    initializing it as a copy of the baseline when missing.
    """
    original_path = original_summary_path(repo_path)
    updated_path = updated_summary_path(repo_path)

    if original_path.exists() and not force:
        if not updated_path.exists():
            shutil.copyfile(original_path, updated_path)
        return original_path

    context = collect_repo_context(repo_path)
    summary = (provider or get_default_provider()).generate_summary(context)

    original_path.parent.mkdir(parents=True, exist_ok=True)
    original_path.write_text(summary, encoding="utf-8")

    if not updated_path.exists():
        shutil.copyfile(original_path, updated_path)

    return original_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the baseline TechDocker project summary."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate even if base_original_summary.md already exists.",
    )
    parser.add_argument("--repo-path", default=".", help="Repository root.")
    arguments = parser.parse_args()

    existed = original_summary_path(arguments.repo_path).exists()
    path = generate_original_summary(arguments.repo_path, force=arguments.force)

    if existed and not arguments.force:
        print(f"Baseline already exists (use --force to regenerate): {path}")
    else:
        print(f"Baseline summary written: {path}")
    print(f"Updated summary: {updated_summary_path(arguments.repo_path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
